version: "3.8"

services:
  server:
    container_name: vscode-remote
    image: vscode-airgap-server:latest
    # If you prefer to build instead of using a prebuilt image, uncomment:
    # build:
    #   context: .
    #   dockerfile: server.Dockerfile
    environment:
      # SSH service inside the container
      # (admin/admin user configured in server.Dockerfile)
      TZ: "UTC"
    volumes:
      # Offline artifacts (including code-server tarball)
      - ./pkgs:/pkgs-host:ro
    networks:
      - vscode-airgap-net
    command: ["/bin/bash", "-c", "/usr/local/bin/startup-info.sh && /usr/sbin/sshd -D"]

networks:
  vscode-airgap-net:
    external: true
